### Get all favorites
GET  http://localhost:3000/api/fav/
### Create a list of favorites
POST http://localhost:3000/api/fav/
Content-Type: application/json

{
  "ownerId": "6265bbdcc99c02dd236a625e",
  "title": "pokemon",
  "description": "Favourite pokemons",
  "URL": "http://www.pokemon.com"
}
### Get a favorite
GET  http://localhost:3000/api/fav/6265c603653444e93d03e61d
### Delete a favourite
DELETE http://localhost:3000/api/fav/6265c677a3fe7966ba87999f

### Auth token
POST http://localhost:3000//auth/local/login
Content-Type: application/json

{
  "email": "asg@afas.es",
  "password": "Pass!123"
}
