### Get all favorites
GET  http://localhost:3000/api/fav/
### Create a list of favorites
POST http://localhost:3000/api/fav/
Content-Type: application/json

{
  "name": "My Favorite List",
  "favs": [
    {
      "title": "Pizza",
      "description": "Pizza is a savory dish of Italian origin, consisting of a usually round, flattened base of leavened wheat-based dough topped with tomatoes, cheese, and various other ingredients (anchovies, olives, meat, etc.) baked at a high temperature, traditionally in a wood-fired oven. In formal settings, like a restaurant, pizza is eaten with knife and fork, but in casual settings it is cut into wedges to be eaten while held in the hand.",
      "url": "http://www.pizza.com"
    },
    {
      "title": "Ice Cream",
      "description": "Ice cream is a food typically made from milk and cream, and sometimes flavored with fruit, nuts, and other ingredients, held together in an airtight container and chilled before serving.",
      "url": "http://www.icecream.com"
    }
  ]
}
### Get a favorite
GET  http://localhost:3000/api/fav/6265c603653444e93d03e61d
### Delete a favourite
DELETE http://localhost:3000/api/fav/6265c677a3fe7966ba87999f

### Auth token
POST http://localhost:3000//auth/local/login
Content-Type: application/json

{
  "email": "asg@afas.es",
  "password": "Pass!123"
}
